import { Report } from "@/types";
import { Separator } from "@/components/ui/separator";

interface ReportTemplateProps {
  report: Report;
}

const ReportTemplate = ({ report }: ReportTemplateProps) => {
  return (
    <div className="bg-background p-8 space-y-6 print:p-12">
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold text-primary">Aqua Lab Analysis Report</h1>
        <p className="text-muted-foreground">Laboratory Report - {report.sampleType.toUpperCase()} Analysis</p>
      </div>

      <Separator />

      <div className="grid grid-cols-2 gap-6">
        <div className="space-y-2">
          <div className="flex justify-between">
            <span className="font-semibold">Report Number:</span>
            <span>{report.reportNumber}</span>
          </div>
          <div className="flex justify-between">
            <span className="font-semibold">Farmer Name:</span>
            <span>{report.farmerName}</span>
          </div>
          <div className="flex justify-between">
            <span className="font-semibold">Sample Type:</span>
            <span className="capitalize">{report.sampleType}</span>
          </div>
        </div>
        <div className="space-y-2">
          <div className="flex justify-between">
            <span className="font-semibold">Generated Date:</span>
            <span>{new Date(report.generatedAt).toLocaleDateString()}</span>
          </div>
          <div className="flex justify-between">
            <span className="font-semibold">Generated By:</span>
            <span>{report.generatedBy}</span>
          </div>
          <div className="flex justify-between">
            <span className="font-semibold">Status:</span>
            <span className="text-primary font-semibold">
              {report.editHistory.length > 0 ? "Revised" : "Original"}
            </span>
          </div>
        </div>
      </div>

      <Separator />

      <div>
        <h2 className="text-xl font-bold mb-4">Test Results</h2>
        <table className="w-full border-collapse">
          <thead>
            <tr className="border-b-2">
              <th className="text-left p-3 bg-accent/10">Test Parameter</th>
              <th className="text-center p-3 bg-accent/10">Result</th>
              <th className="text-center p-3 bg-accent/10">Unit</th>
              <th className="text-center p-3 bg-accent/10">Normal Range</th>
            </tr>
          </thead>
          <tbody>
            {report.testResults.map((result, index) => (
              <tr key={result.testId} className={index % 2 === 0 ? "bg-accent/5" : ""}>
                <td className="p-3 font-medium">{result.testName}</td>
                <td className="p-3 text-center font-semibold">{result.value}</td>
                <td className="p-3 text-center">{result.unit || "-"}</td>
                <td className="p-3 text-center">{result.normalRange || "-"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {report.remarks && (
        <>
          <Separator />
          <div>
            <h3 className="text-lg font-bold mb-2">Remarks / Comments</h3>
            <p className="text-sm whitespace-pre-wrap bg-accent/5 p-4 rounded-lg">{report.remarks}</p>
          </div>
        </>
      )}

      <Separator />

      <div className="text-sm text-muted-foreground space-y-1">
        <p>This is a computer-generated report from Aqua Lab Management System</p>
        <p>For any queries, please contact the laboratory</p>
      </div>

      {report.editHistory.length > 0 && (
        <div className="text-xs text-muted-foreground border-t pt-4">
          <p className="font-semibold">Revision History:</p>
          {report.editHistory.map((edit, index) => (
            <p key={index}>
              • {edit.changes} by {edit.editedBy} on {new Date(edit.editedAt).toLocaleString()}
            </p>
          ))}
        </div>
      )}
    </div>
  );
};

export default ReportTemplate;
